// <auto-generated />
using System;
using Lecture01.Sync.Http.CatsService.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lecture01.Sync.Http.CatsService.Migrations
{
    [DbContext(typeof(CatsDbContext))]
    partial class CatsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lecture01.Sync.Http.CatsService.DataAccess.Entities.Cat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AgeMonths")
                        .HasColumnType("integer");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsVaccinated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("WeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            AgeMonths = 24,
                            Breed = "Британская короткошёрстная",
                            IsVaccinated = true,
                            Name = "Барсик",
                            WeightKg = 5.2000000000000002
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            AgeMonths = 36,
                            Breed = "Сибирская",
                            IsVaccinated = true,
                            Name = "Мурка",
                            WeightKg = 4.7999999999999998
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333333"),
                            AgeMonths = 12,
                            Breed = "Дворовая",
                            IsVaccinated = false,
                            Name = "Васька",
                            WeightKg = 3.8999999999999999
                        },
                        new
                        {
                            Id = new Guid("a4444444-4444-4444-4444-444444444444"),
                            AgeMonths = 8,
                            Breed = "Мейн-кун",
                            IsVaccinated = true,
                            Name = "Рыжик",
                            WeightKg = 3.1000000000000001
                        },
                        new
                        {
                            Id = new Guid("a5555555-5555-5555-5555-555555555555"),
                            AgeMonths = 18,
                            Breed = "Шотландская вислоухая",
                            IsVaccinated = false,
                            Name = "Кузя",
                            WeightKg = 4.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
