services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: cats_odata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - cats-odata-data:/var/lib/postgresql/data

volumes:
  cats-odata-data:
